### ISSUE TITLE
Item filter is broken

### ISSUE THREAD

**Issue by ank-everstake** [BGmot/zabbix-module-latest-data#1] opened 2021-08-26 07:42 UTC
When module is enabled item filter in latest data only works half the time.
You can set any filter value and press apply 4 times in a row and each second time you will get the old filter back.

How to replicate:
1. Set item filter ("Name") to value1
2. Press Apply
3. Set item filter ("Name") to value2
4. Press Apply 4 times in a row - you will get : new, old, new, old

**Comment by BGmot** [comment] 2021-08-28 02:29
Fixed by https://github.com/BGmot/zabbix-module-latest-data/commit/dda1b82cc63cfe4f27a10321ec394bf4d75960b5

**Comment by ank-everstake** [comment] 2021-08-28 16:25
Seems the same bug exists in tag filter, even on v1.0.1

Here is the demo that shows it:
https://user-images.githubusercontent.com/56387196/131224367-e072dd24-26b1-4052-9e81-fa147b228f4c.mp4

**Comment by xenadmin** [comment] 2021-08-28 17:29
@ank-everstake Maybe you need to create a second bug report, as this one is closed?

**Comment by ank-everstake** [comment] 2021-08-28 17:37
I think that we should reopen the existing as it may be connected.

**Comment by BGmot** [comment] 2021-08-28 19:29
Reopen. I will take a look again.

**Comment by BGmot** [comment] 2021-09-02 22:13
Finally found some time to take a look more closely and... I feel stupid - I just can't reproduce, please see attachment.

https://user-images.githubusercontent.com/1423807/131923053-d3d091e7-fbb3-4f9e-a6f6-4596286fdc7d.mp4

**Comment by ank-everstake** [comment] 2021-09-03 13:44
Please check filtering not in the name field (items), but in the **tag filter**.

**Comment by BGmot** [comment] 2021-09-03 14:56
Up to this point we talked about Name field, right? So we are all on the same page. I see the bug in Tag filter, will try to fix.

**Comment by xenadmin** [comment] 2021-09-06 07:57
>Up to this point we talked about Name field, right?

Yes, you are right. That's why I suggested to create a second issue, instead of re-opening this one. But to be fair @ank-everstake said his video is about tags. But most important I'm glad you will take a look at this issue =)

**Comment by BGmot** [comment] 2021-09-08 03:30
Guys please test version v1.0.2.

**Comment by ank-everstake** [comment] 2021-09-10 18:58
The fix seems to work ok on **v5.4.4**.

**Comment by BGmot** [comment] 2021-09-12 14:02
Thanks for testing. Closing the issue.

**Closed by BGmot** 2021-09-12 14:02 UTC
Labels: bug
